# Generated by Django 3.1.6 on 2021-08-16 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_tag', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=100000)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.CharField(max_length=50)),
                ('author_sem', models.CharField(max_length=50)),
                ('author_insta_link', models.CharField(max_length=200)),
            ],
        ),
    ]
